# Change these first
owner: se95lopez # Your GitHub organization or username, where this repository lives
repo: lighthouse-uptime # The name of this repository

sites:
  - name: Lighthouse RES
    url: https://res-test-586746141603.us-central1.run.app/health
  - name: Lighthouse RPS
    url: https://rps-health-proxy-586746141603.us-central1.run.app
  - name: Lighthouse Document Converter
    url: https://documenttotext-586746141603.us-central1.run.app/dummy
  - name: Lighthouse User Management
    url: https://supabase-user-functions-586746141603.us-central1.run.app/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /lighthouse-uptime
  logoUrl: https://www.google.com/imgres?q=lighthouse%20hiring%20logo&imgurl=https%3A%2F%2Fmedia.licdn.com%2Fdms%2Fimage%2Fv2%2FD4D0BAQFTnY8SaTJ1Jg%2Fcompany-logo_200_200%2Fcompany-logo_200_200%2F0%2F1733240982437%2Flighthouse_hiring_innovations_logo%3Fe%3D2147483647%26v%3Dbeta%26t%3D9lS-jiorRpzbcyQY7kGeQwVz0-HSBJCtspqz-lH7F98&imgrefurl=https%3A%2F%2Fca.linkedin.com%2Fcompany%2Flighthouse-hiring-innovations&docid=BNiNf4a_Ho0QlM&tbnid=kJRjtTzTuUd3tM&vet=12ahUKEwjesb2614eOAxWOHNAFHRy5K-oQM3oECBgQAA..i&w=200&h=200&hcb=2&ved=2ahUKEwjesb2614eOAxWOHNAFHRy5K-oQM3oECBgQAA
  name: Lighthouse Status Website
  introTitle: "**Lighthouse** Services Server Status"
  introMessage: All **Lighthosue** services and their statuses will be monitored here
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
